### ISSUE TITLE
Cannot convert value of type 'Error' to expected argument type 'String?'

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#13]
When running on iOS the build fails due to the error "Cannot convert value of type 'Error' to expected argument type 'String?'" which is thrown in 10 different places in Plugin.swift.  I don't know Swift very well so right now i'm just adding "" around `error` where these errors are thrown. 

<img width="910" alt="Screen Shot 2020-06-05 at 10 18 41 AM" src="https://user-images.githubusercontent.com/25699262/83887154-0bf5d200-a716-11ea-8d35-48b2b4eca0c6.png">

**Comment by nprail** [comment]
@kyleabens What XCode and Capacitor version are you on?

**Comment by nprail** [comment]
This appears to be due to a change in Capacitor's API in 2.0. There is now a `call.error` method that takes an `Error` object while the `call.reject` method takes a string. The odd thing is, this change isn't documented anywhere. Not even in their release notes. And the docs still show using `call.reject` with an `Error` object.
