### ISSUE TITLE
Tap to Pay iOS "An incompatible reader was detected."

### ISSUE THREAD

**Issue by philmmoore** [eventOneHQ/capacitor-stripe-terminal#130]
I've requested the Tap to Pay entitlement for iOS and enabled this in Xcode but not having any joy when actually trying to connect to either a simulator or even a physical device.

It is able to discover the physical device but when it attempts to connect it returns "An incompatible reader was detected." which points to the error SCPErrorIncompatibleReader = 3030 in the Stripe Terminal SDK. 

I'm using SDK v3 from zolfa-capacitor-stripe-terminal by @zolfariot, am I missing some steps in the setup that aren't documented? 

The physical device is an iPhone 15 Pro Max on iOS 17.1 the only thing I note is that I'm not seeing any of the native setup screens for tap to pay.

Thanks

**Comment by philmmoore** [comment]
Ok so it turns out that it was me just being stupid! 

I was using the localMobile discovery method but still using the connectBluetoothReader method and didn't realise there was a connectLocalMobileReader.

**Comment by kyleabens** [comment]
@philmmoore Did you ever run into an issue when you attempted to connect with connectLocalMobileReader where the following error is thrown?

"The operation could not be completed because the merchant account is not linked. Reconnect the app to the reader."

I can't seem to get around this and I have followed all steps.  Not even sure what it means.
