### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#16]
I have a couple questions/fixes concerning the usage example.

1. I'm assuming `new StripeTerminal` should be `new StripeTerminalPlugin` based on what's imported.

```typescript
import {
  StripeTerminalPlugin,
  DeviceType,
  DiscoveryMethod
} from 'capacitor-stripe-terminal'

// First, initialize the SDK
const terminal = new StripeTerminal({
  fetchConnectionToken: async () => {
    const resp = await fetch('https://your-backend.dev/token', {
      method: 'POST'
    })
    const data = await resp.json()

    return data.secret
  }
})
```

2. When retrieving the payment intent, the variable `pi` is never used.  Should it be used as an argument in `processPayment` or is it used when capturing the payment intent?

```typescript
// retrieve the payment intent
  const pi = await terminal.retrievePaymentIntent(
    'your client secret created server side'
  )

  // collect the payment method
  await terminal.collectPaymentMethod()

  // and finally, process the payment
  await terminal.processPayment()
```

**Comment by nprail** [comment]
1. That is correct. It should be `StripeTerminalPlugin`. 
2. No, you don't have to pass `pi` into `collectPaymentMethod` or `processPayment`. That is why you MUST call `retrievePaymentIntent` before. It caches the payment intent in Swift and then uses that PI object for `processPayment`. It's a technical limitation due to the fact that you can't just pass JS objects into Swift code (see #6).
