### ISSUE TITLE
retrievePaymentIntent returns null on browser for a connected Verifone P400

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#37]
**Describe the bug**
`stripeTerminalPlugin.retrievePaymentIntent(clientSecret)` returns null on browser for a connected Verifone P400.  Stripes docs use `collectPaymentMethod(clientSecret)`.  This may be the issue but collectPaymentMethod doesn't have any arguments in this plugin.

**To Reproduce**
Connect to a Verifone P400 in the browser with an application that utilizes this plugin and attempt to retrievePaymentIntent with clientSecret.

**Expected behavior**
It should return the payment intent object

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: Brave or Chrome
- Version latest version

**Comment by kyleabens** [comment]
Never mind I realized I can still pass it to `retrievePaymentIntent(clientSecret)` and simply get the payment intent object from `collectPaymentMethod `

**Comment by nprail** [comment]
Yeah, this is expected behavior (#6). The JS SDK doesn't have a `retrievePaymentIntent` method so `retrievePaymentIntent` in the web plugin only sets the client secret then returns `null`. 

If I remember correctly, Stripe doesn't have a publicly documented way of fetching payment intents with only the client secret. Besides with Stripe.js or the native SDKs. I could fetch it with Stripe.js but that's another dependency that isn't needed and you can get the PI from `collectPaymentMethod` like you mentioned.

**Comment by nprail** [comment]
Actually, there's an API for getting a PI but it requires the public key and client secret. The plugin never has the public key since Terminal uses tokens. Although, I wonder if using a token on that endpoint would work. I'll have to try that tomorrow. 

https://stripe.com/docs/api/payment_intents/retrieve?lang=curl
