### ISSUE TITLE
Ionic v1 + AngularJS ES5 project usage

### ISSUE THREAD

**Issue by iborschca** [eventOneHQ/capacitor-stripe-terminal#87]
Hey guys! Thank you so much for such amazing and useful plugin. I am a bit disappointed because I am having ES5 Ionic + AngularJS project and I want to use this plugin but I can't. I am wondering is there any chance I can leverage your amazing plugin with my old project without modernizing it entirely?

**Comment by nprail** [comment]
In theory, you should be able to use it with ES5. Try importing this way:

```javascript
const {
  StripeTerminalPlugin,
  DiscoveryMethod
} = require('capacitor-stripe-terminal')
```

Then you'd have to use promises instead of async/await. 

Like I said, this should work in theory. I've not actually tried it.

**Comment by iborschca** [comment]
Unfortunately AngularJS is using AMD (Asynchronous module definition) I can just use RequireJS. But I found the place where the framework is importing it.
![image](https://user-images.githubusercontent.com/97372700/152099695-a2ea14cf-fd1d-4a26-be0c-6778b499f4d5.png)
On the screenshot you can see create() and discoverReaders() function. Can you please help me to initializes an object instance of a class with help of these functions?

**Comment by iborschca** [comment]
Can't create an instance ((
![image](https://user-images.githubusercontent.com/97372700/152251996-ace07141-db7e-4f5c-81e8-4bc595ba048c.png)

**Comment by nprail** [comment]
Yeah, unfortunately that does not work because the `StripeTerminal` class that is exposed by Capacitor is not the same as the `StripeTerminalPlugin` class that this plugin exports. `Capacitor.Plugins.StripeTerminal` is the native bridge directly generated by Capacitor. `StripeTerminalPlugin` contains a considerable amount of wrapper code that you are loosing by using `StripeTerminal` directly and it is not how this plugin is intended to be used. 

AMD is not supported and isn't something I want to add support for.

You could use `StripeTerminal` exported by Capacitor but you would effectively have to re-create this entire file in your code to use it correctly: https://github.com/eventOneHQ/capacitor-stripe-terminal/blob/master/src/plugin.ts
