### ISSUE TITLE
Stripe Terminal Test Card doesn't work?

### ISSUE THREAD

**Issue by joshstrange** [eventOneHQ/capacitor-stripe-terminal#97]
**Describe the bug**
I just bought one the Stripe M2 readers and one of their physical test cards. For some reason it keeps giving me a ReaderDisplayMessage of `6` (The card could not be read. Try another read method on the same card, or use a different card.). I've tried contactless and dip, same message either way. If I try a real card it will read it correctly then fail when it attempts to process the payment (understandable) with the following error:

```
Error: Your card was declined. Your request was in test mode, but used a non test (live) card. For a list of valid test cards, visit: https://stripe.com/docs/testing.
```

Again, I would expect this trying to use a real card in the test environment. My problem is the physical test card from Stripe is not working and I'm not sure where the issue is.

Has anyone here successfully used the "Stripe Terminal Test Card" with the "Stripe M2 Reader"? Or with any of the supported readers?

**Comment by Irrelon** [comment]
@joshstrange  I've got a test card and multiple reader types and I'm currently trying to integrate with this plugin. I've noticed quite a few issues with it around (undocumented) behaviour when a payment fails to process.

If you attempt to make a payment again directly after failure the plugin can respond will errors like "trying to discoverReaders when it's already running" or somesuch error (can't remember exact phrasing) and yet, if you attempt to make a payment it says "SDK cannot connect to reader until discoverReaders() is called" or something like that.

I'm fairly concerned about rolling out with the plugin because of this. 

I've yet to test the scenario where I'm expecting a successful payment because I've been trying to get the plugin to work when failure occurs.

When I get a moment I'll go through a successful flow test using the test card and let you know what I get back!

Have you noticed the kind of issues I'm describing above?

**Comment by joshstrange** [comment]
@Irrelon I have not seen those issues myself. I know my own UI needs improvement for reflecting the current state of the reader but so far I have not been able to pin any of those issues on this plugin.

My card reading issue appears to be due to a bad batch of Stripe Test cards (multiple months back and forth with Stripe support and 10 new cards sent to me, most from the same bad batch, before it was identified). I actually haven't tested the cards they finally sent that they said would work, I was too close to my event that used this system to take the time.

I can say that we ran over $20K through the in-person card readers using this plugin without issue for our event. I was only using iPads so I can't speak to the android side of things but I wanted to let you know it did work for us.

**Comment by Irrelon** [comment]
@joshstrange thanks, that's really good to know! I suppose failure is a rare exception anyway, but I like apps to handle things really REALLY well when failure does occur so I'm gonna have to do more experimentation and testing. I'll still report back and let you know if a successful test card transaction works :)

Thanks for your info though, it's put my mind at ease a lot!!

**Comment by nprail** [comment]
Closing this since it seems to be a non-issue. 

@Irrelon are you still seeing strange SDK behavior in other areas? If so, could you please create new issues for those?

**Comment by joshstrange** [comment]
Sorry I never replied back to this, this library works fine with Stripe Test cards, I got a bad batch initially and I have since tested them and they work perfectly. Just wanted to leave this as a comment if someone else stumbles on it.
